language: go
install:
    - go get github.com/alecthomas/gometalinter
    - go get github.com/kisielk/errcheck
    - go get github.com/justsocialapps/assert
script:
    - gometalinter .
    - go test ./...
